#!/usr/bin/env node

/**
 * =================================================================
 * LUMIÈRE Automated Client Onboarding & White-label Setup Script
 * Sets up a completely customized instance for a new client in seconds.
 * =================================================================
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const ask = (query, defaultValue) => {
    return new Promise(resolve => {
        rl.question(`${query} ${defaultValue ? '(\' + defaultValue + \'): ' : ': '}`, answer => {
            resolve(answer.trim() || defaultValue || '');
        });
    });
};

const runOnboarding = async () => {
    console.log(`
    ========================================================
    🌸 LUMIÈRE White-Label Onboarding Wizard
    Configure a fresh, production-ready store for your client!
    ========================================================
    `);

    const storeNameAr = await ask('Store Name in Arabic (اسم المتجر بالعربية)', 'لوميير باريس');
    const storeNameEn = await ask('Store Name in English (اسم المتجر بالإنجليزية)', 'LUMIERE Paris');
    const adminEmail = await ask('Administrator Email (بريد المدير)', 'admin@clientdomain.com');

    const defaultPass = 'Client_' + crypto.randomBytes(4).toString('hex') + '!';
    const adminPassword = await ask('Administrator Password (كلمة مرور المدير)', defaultPass);

    const defaultCurrency = await ask('Default Currency (SAR, AED, USD, etc.)', 'SAR');
    const whatsapp = await ask('Customer Support WhatsApp Number (مع الرمز الدولي)', '+966501234567');

    console.log('\n⚙️  Generating cryptographic JWT security secret...');
    const jwtSecret = crypto.randomBytes(32).toString('hex');

    const envContent = `# =================================================================
# Store Configuration for ${storeNameEn}
# Auto-generated by LUMIERE Onboarding Wizard on ${new Date().toISOString()}
# =================================================================

PORT=4000
NODE_ENV=production

# Security
JWT_SECRET=${jwtSecret}

# Initial Admin Account
ADMIN_EMAIL=${adminEmail}
ADMIN_PASSWORD=${adminPassword}

# Brand & Localization
STORE_NAME_AR=${storeNameAr}
STORE_NAME_EN=${storeNameEn}
STORE_LOGO_TEXT=${storeNameEn.toUpperCase()}
STORE_LOGO_SUB=LUXURY CARE
DEFAULT_CURRENCY=${defaultCurrency}
SUPPORT_EMAIL=${adminEmail}
SUPPORT_WHATSAPP=${whatsapp}

# Database
DATABASE_FILE=./data/lumiere.db
`;

    const envPath = path.resolve(__dirname, '../.env');
    fs.writeFileSync(envPath, envContent, 'utf8');
    console.log('✓ Successfully wrote .env configuration file.');

    // Run database migrations
    console.log('\n🗄️  Running database migrations...');
    const { runMigrations } = require('../src/database/migrator');
    await runMigrations();

    // Ask about demo products
    const seedDemo = await ask('Do you want to seed demo skincare products? (y/n)', 'y');
    if (seedDemo.toLowerCase() === 'y') {
        const { runSeeds } = require('../src/database/seeder');
        await runSeeds();
    } else {
        // Seed admin only
        const seederAdmin = require('../src/database/seeds/001_seed_admin');
        const { query, run } = require('../src/database/db');
        await seederAdmin.run({ query, run });
        console.log('✓ Initialized clean database without demo products.');
    }

    console.log(`
    ========================================================
    🎉 Setup Complete! Store is 100% ready for the client:
    --------------------------------------------------------
    📍 Store URL:       http://localhost:4000
    📊 Admin Hub:       http://localhost:4000/admin/index.html
    🔑 Admin Email:     ${adminEmail}
    🔑 Admin Password:  ${adminPassword}
    ========================================================
    `);

    rl.close();
    process.exit(0);
};

runOnboarding().catch(err => {
    console.error('Setup failed:', err);
    rl.close();
    process.exit(1);
});
